CarRentalSystem/Models/Clint.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CarRentalSystem.Models
{
    public class Clint
    {
   
        public int id { set; get; }
        [Required(ErrorMessage="name is required.")]
        public string Name { set; get; }
        [Required(ErrorMessage = "ssn is required.")]
        public int Ssn { set; get; }
        [Required(ErrorMessage = "age is required.")]
        public int Age { set; get; }
        [Required(ErrorMessage = "email is required.")]
        [EmailAddress]
        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage= " please enter valid email.")]
        public string Email { set; get; }
        [Required(ErrorMessage = "username is required.")]
        public string username { set; get; }
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 8 )]
        [Required(ErrorMessage = "password is required.")]
        [DataType(DataType.Password)]
        public string password { set; get; }
        [Compare("password", ErrorMessage="please confirm your password.")]
        [DataType(DataType.Password)]
        public string confirmpassword { set; get; }
        [Required(ErrorMessage = "phone is required.")]

        public int phone { set; get; }
        public string PreferedCarType { set; get; }

        public Category categorytype { set; get; }
        
        [Display(Name = "Prefered Car type")]
        public int categorytypeid { set; get; }
        public bool blockstate { set; get; }

    }
} 

CarRentalSystem/Controllers/ClintController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using CarRentalSystem.Models;
using CarRentalSystem.ViewModel;
using Twilio;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;
using Twilio.TwiML;
using Twilio.AspNet.Mvc;
using System.Text.RegularExpressions;

namespace CarRentalSystem.Controllers
{
    public class ClintController : Controller
    {
        private ApplicationDbContext db;
        private  CarClintViewModel Viewmodel;
        public SearchCarViewmodel searchmodel;
        public ClintController()
        {
            db = new ApplicationDbContext();
            Viewmodel = new CarClintViewModel();
            searchmodel = new SearchCarViewmodel();
        }
        // GET: Clint
        //from login to index-->clint object  
        [Route("Clint/Home/{id}")]
        public ActionResult Home(int id)
        {
            var categories = db.categories.ToList();
            var currentclint = db.clints.SingleOrDefault(c => c.id == id);
            Viewmodel.categories = categories;
            Viewmodel.clint = currentclint;

            searchmodel.categories = Viewmodel.categories;
            Viewmodel.viewmodel = searchmodel;
            return View(Viewmodel);   
        }
        [HttpPost]
        [Route("Clint/result")]
        public ActionResult result(SearchCarViewmodel viewmodel)
        {
            if (!ModelState.IsValid)
            {
                if (viewmodel.car.color != null && !viewmodel.car.color.All(char.IsLetter))
                {
                    viewmodel.colorstate = 1;
                    viewmodel.messageerror = "the color field must be word without any number";
                    return Json(new { state = false, viewmodel = viewmodel});
                }else
                {
                  return Json(new { state = false, viewmodel = viewmodel });
                }
                
            }
            else
            {
                if (!viewmodel.car.color.All(char.IsLetter))
                {
                    viewmodel.colorstate = 1;
                    viewmodel.messageerror = "the color field must be word without any number";
                    return Json(new { state = false, viewmodel = viewmodel });
                }
                else
                {
                    return Json(new { state = true, viewmodel = viewmodel });
                }
            }
        }

        public ActionResult submitnotvalid(SearchCarViewmodel viewmodel)
        {
            viewmodel.categories = db.categories.ToList();
            return PartialView("searchform", viewmodel);
            //return Content("calleeeed");
        }
        public ActionResult ShowCars(SearchCarViewmodel viewmodel) 
        {
            var Carlist = db.cars.Include(c => c.categorytype).ToList().
                   Where(c => c.categorytypeid == viewmodel.car.categorytypeid && c.color == viewmodel.car.color && c.Model == viewmodel.car.Model && c.NumberOfChairs == viewmodel.car.NumberOfChairs && c.RentAmount <= viewmodel.car.RentAmount);
            if (Carlist.Count()>=1)
            {
                Viewmodel.cars = Carlist;
                Viewmodel.clint = db.clints.SingleOrDefault(c => c.id == viewmodel.id);
                Viewmodel.viewmodel = viewmodel;
                return PartialView(Viewmodel);
            }
            else 
            {
                return Content("<span class='cardon'texist'> this Car doesn't exists</span>");
            }
            
        }

        [HttpPost]
        //[Route("Clint//Information/")]
        public ActionResult ShowInformationAboutCar( int SSn,int id) 
        {
            var car = db.cars.Include(c => c.categorytype).SingleOrDefault(c => c.id == id);
            var clint = db.clints.SingleOrDefault(c => c.Ssn == SSn);
            Viewmodel.car = car;
            Viewmodel.clint = clint;
            return View(Viewmodel);
        }
        [HttpPost]
        [Route("Clint/Reservation")]
        public ActionResult Reservation(CarClintViewModel viewmodel)
        {
          if (viewmodel.car.To != null && viewmodel.car.From != null) 
             {
                if (viewmodel.car.To > viewmodel.car.From)
                {
                    try
                    {
                        //return Content("<h1>"+viewmodel.car.Name+"</h1>"+"hhhhhhhhh");
                        var car = db.cars.Include(c => c.categorytype).SingleOrDefault(c => c.id == viewmodel.car.id);
                        
                        car.From = viewmodel.car.From;
                        car.To = viewmodel.car.To;
                        car.clintid = viewmodel.clint.id;
                        var clint = db.clints.SingleOrDefault(c => c.id == viewmodel.clint.id);
                        db.SaveChanges();
                        TimeSpan Duration = new TimeSpan();
                        Duration = (TimeSpan)(viewmodel.car.To - viewmodel.car.From);
                        SendSms("+2"+clint.phone,"you are successfully rented this car :"+ car.Name+ " from :" + viewmodel.car.From + " :to:" + viewmodel.car.To + " " + " and the ending duration of rent is :" + Duration.Duration());
                        SendSms("+201276134569","The clint :"+clint.Name+"has id :"+clint.id+" have been rented this car :"+car.Name +" it's type " +car.categorytype.Name);
                        return Json(new { state = true, viewmodel = viewmodel, message = "the message it's on the way to you that confim you are rented thid car: "+car.Name });
                        //return Content();
                    }
                    catch (Exception e)
                    {
                        return Content(e.ToString());
                    }
                    
                }
                else 
                {
                    viewmodel.fromstate = 1;
                    viewmodel.tostate = 1;
                    viewmodel.messageerror = "the to date must be bigger than from date";
                    return Json(new { state = false, viewmodel = viewmodel });
                } 
            }else
            {
                if (viewmodel.car.From == null)
                {
                    viewmodel.fromstate = 1;
                    viewmodel.messageerror = "this field is required";
                    return Json(new { state = false, viewmodel = viewmodel });
                }
                else /*if (viewmodel.car.From == null) */
                {
                    viewmodel.tostate = 1;
                    viewmodel.messageerror = "this field is required";
                    return Json(new { state = false, viewmodel = viewmodel });
                }
                  
            }
           

        }
        public ActionResult SendSms(String Reciever, String Message)
        {
            //if (IsValidNum(Reciever) == true){
            // var accountSid= ConfigurationManager.AppSettings["TwilioAccountSid"];
            var accountSid = "ACc0bdc28f6febf87ff77eaa9e34f71996";
            var authToken = "368c61efd2522d221727bec00513c4b3";
            TwilioClient.Init(accountSid, authToken);
            //var to = new PhoneNumber(ConfigurationManager.AppSettings["MyPhoneNumber"]);
            var to = new PhoneNumber(Reciever);
            var from = new PhoneNumber("+18317775716");
            try
            {
                var message = MessageResource.Create(
                to: to,
                from: from,
                body: Message);
            }
            catch (Exception e)
            {
                return Content(e.ToString());
            };


            return Content(Message);
            //}
            //else { return Content("there is an ERROR"); }
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }
        // GET: Clint
        public ActionResult Index()
        {
            var clints = db.clints.ToList();
            return View(clints);

        }
        public ActionResult deleteClint(int id)
        {
            var clint = db.clints.Single(m => m.id == id);
            db.clints.Remove(clint);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult BlockClint(int id)
        {
            var clint = db.clints.Single(m => m.id == id);
            return View();
        }

        bool IsValidNum(String Reciever)
        {
            return Regex.Match(Reciever, @"^(\+[0-9]{9})$").Success;
        }

    }

}
 

CarRentalSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarRentalSystem.Models;

namespace CarRentalSystem.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Car p)
        {
            if (Session["cart"] != null)
            {
                var ls = Session["cart"] as List<Car>;
                ls.Add(p);
            }
            else
            {
                Session["cart"] = new List<Car>() { p };   
            }
            ModelState.Clear();
            RedirectToAction("Index", "Home");
            return View();
        }
    }
}

CarRentalSystem/Views/Clint/Home.cshtml
@model CarRentalSystem.ViewModel.CarClintViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

    <h2>Select Car</h2>
     
     <div id="partial">
         @Html.Partial("~/Views/Clint/searchform.cshtml",Model.viewmodel)
     </div>     
   
    <div id="table">

    </div>

CarRentalSystem/Views/Clint/Reservationform.cshtml
@model CarRentalSystem.ViewModel.CarClintViewModel

<script src='@Url.Content("~/Scripts/jquery-1.10.2.js")'></script>
<script>
    $(document).ready(function () {
        $("#Rentform").on("submit", function () {
            alert("i will send");
            var viewmodel = $(this).serialize();
            $.ajax({
                url: '@Url.Action("Reservation", "Clint")',
                type: "POST",
                data: viewmodel,
                cache: false,
                async: true,
                success: function (rt, st, xhr) {
                    if (st == "error") {
                        alert("Error :" + xhr.status + " " + xhr.statusText);
                    }
                    else {
                        
                        if (rt.state == false) {
                            if (rt.viewmodel.fromstate == 1 && rt.viewmodel.tostate == 1)
                            {
                                alert("i will send");
                                $("#errormessageFrom,#errormessageTo").css({ "color": "red","display":"block" });
                                $("#car_From,#car_To").attr({ "id": "input-validation-error" });
                                $("#errormessageFrom,#errormessageTo").html(rt.viewmodel.messageerror);

                            } else if (rt.viewmodel.formstate == 1) {
                                alert("i will send");
                                $("#errormessageFrom").css({ "color": "red", "display": "block" });
                                $("#car_From").attr({ "id": "input-validation-error" });
                                $("#errormessageFrom").html(rt.viewmodel.messageerror);
                            } else if (rt.viewmodel.tostate == 1) {
                                alert("i will send");
                                $("#errormessageTo").css({ "color": "red", "display": "block" });
                                $("#car_To").attr({ "id": "input-validation-error" });
                                $("#errormessageTo").html(rt.viewmodel.messageerror);
                            }

                        } else
                        {
                            alert("i will send");
                            $("#partil").slideUp(1000);
                            $("#result").html(rt.message);
                        }
                    }
                }

              });

            return false;
            
        });

    });
</script>
<div class="form-inline">
    @using (Html.BeginForm("Reservation", "Clint", FormMethod.Post, new { id = "Rentform" }))
    {
       <div class="form-group">
                @Html.LabelFor(c => c.car.From)
                <input type="datetime-local" name="car.From" id="car_From" placeholder="Enter the start time" class="form-control">
           <span class="field-validation-error" id="errormessageFrom" style="display:none"> @Model.messageerror </span>
       </div>
       <div class="form-group">
                @Html.LabelFor(c => c.car.To)
                <input type="datetime-local" name="car.To" id="car_To" placeholder="Enter the end time" class="form-control">
                <span class="field-validation-error" id="errormessageTo" style="display:none"> @Model.messageerror </span>
        </div>
        
        @Html.HiddenFor(c => c.car.id)
        @Html.HiddenFor(c => c.clint.id)

        <div class="form-group">
            <input type="Submit" class="btn btn-danger" value="Rent">
        </div>
    }
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" class="paypalform">
        <input type="hidden" name="cmd" value="_cart">
        <input type="hidden" name="upload" value="1">
        <input type="hidden" name="business" value=" tito68932-facilitator@gmail.com">
        <input type="hidden" name="item_name_1" value="Aggregated items">
        <input type="hidden" name="amount_1" value="3.00">
        <input type="submit" value="PayPal">
    </form>

</div>

CarRentalSystem/Views/Clint/ShowCars.cshtml
@model CarRentalSystem.ViewModel.CarClintViewModel

<table class="table">
        <caption><center>Results</center></caption>
        <tr>
            <th>
                @Html.DisplayNameFor(c => c.car.Name)
            </th>
            <th>
                @Html.DisplayNameFor(c => c.car.Model)
            </th>
            <th>
                @Html.DisplayNameFor(c => c.car.color)
            </th>
            <th>
                @Html.DisplayNameFor(c => c.car.RentAmount)
            </th>
            <th>
                @Html.DisplayNameFor(c => c.car.State)
            </th>
            <th>
                Show Information
            </th>
        </tr>

        @foreach (var item in Model.cars)
        {
            <tr>
                <td>
                    @Html.DisplayFor(c => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(c => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(c => item.color)
                </td>
                <td>
                    <span>$</span>@Html.DisplayFor(c => item.RentAmount)
                </td>
                @{
                    if (item.State == true)
                    {
                <td>
                    Un Availabe
                </td>
                    }
                    else
                    {
                <td>
                    Availabe
                </td>
                    }
                }
                <td>
                   @* @Html.ActionLink("Information", "ShowInformationAboutCar", new { SSn = Model.clint.Ssn, category = item.categorytype.Name, id = item.id }, new { @class = "btn btn-primary" })*@
                   @using (Html.BeginForm("ShowInformationAboutCar", "Clint", FormMethod.Post))
                   {
                        
                     <input type="text" name="SSn" value="@Model.clint.Ssn" hidden/>
                     <input type="text" name="id" value="@item.id " hidden />
                     <input type="submit" class="btn btn-primary" value="Information" id="submitformshow" />
                   }
                </td>
            </tr>
                    }

 </table>

CarRentalSystem/Views/Clint/ShowInformationAboutCar.cshtml
@model CarRentalSystem.ViewModel.CarClintViewModel

@{
    ViewBag.Title = "ShowInformationAboutCar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ShowInformationAboutCar</h2>
<script src='@Url.Content("~/Scripts/jquery-1.10.2.js")'></script>
<script>
    $(document).ready(function () {
        $("#showForm").click(function () {
            $("#partil").slideDown(1000);
        });
    });
 </script>
<div>
    <h4>@Model.car.categorytype.Name</h4>
    <hr />
    <h2>Information</h2>

    <div>
        <h4>@Model.car.categorytype.Name</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
               @Html.DisplayNameFor(model => model.car.ImagePath)
           </dt>
            <dd>
              <img src="@Url.Content(Model.car.ImagePath)" alt="@Model.car.Name" width="200" height="200" />
           </dd>
            <dt>
                @Html.DisplayNameFor(model => model.car.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.car.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.car.color)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.car.color)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.car.Model)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.car.Model)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.car.RentAmount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.car.RentAmount)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.car.State)
            </dt>
            @{if (Model.car.State == true)
            {
                <dd>
                    Un Available
                </dd>
            }
            else
            {
                <dd>
                    Available
                </dd>
            }
            }
        </dl>
        <div>
            @{if (Model.car.State == true)
            {
                <button class="btn-danger" disabled>Rent</button>
            }
            else
            {
                <button class="btn-danger" id="showForm">Rent</button>

            }
            }
        </div>
        <div id="partil">
            @Html.Partial("Reservationform",Model)
        </div>
         <div id="result">

        </div>
   </div>
 </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

CarRentalSystem/Views/Clint/searchform.cshtml
@model CarRentalSystem.ViewModel.SearchCarViewmodel
<script src='@Url.Content("~/Scripts/jquery-1.10.2.js")'></script>
<script>
             $(document).ready(function () {
                 $("#Showcarform").on("submit", function () {
                     alert("i will send");
                     var viewmodel = $(this).serialize();
                     $.ajax({
                         url: '@Url.Action("result", "Clint")',
                         type: "POST",
                         data: viewmodel,
                         cache: false,
                         async: true,
                         success: function (rt, st, xhr) {
                             if (st == "error") {
                                 alert("Error :" + xhr.status + " " + xhr.statusText);
                             }
                             else {
                                 alert("i will send");
                                 if (rt.state == true) {
                                     var viewmodel = rt.viewmodel;
                                     $.ajax({
                                         url: '@Url.Action("ShowCars", "Clint")',
                                         type: "POST",
                                         data: viewmodel,
                                         cache: false,
                                         async: true,
                                         success: function (rt, st, xhr) {
                                             if (st == "error") {
                                                 alert("Error :" + xhr.status + " " + xhr.statusText);
                                             }
                                             else {
                                                 $("#table").html(rt);
                                             }
                                         }
                                     });
                                 } else
                                 {

                                     var viewmodel = rt.viewmodel;
                                     $.ajax({
                                         url: '@Url.Action("submitnotvalid", "Clint")',
                                         type: "POST",
                                         data: viewmodel,
                                         cache: false,
                                         async: true,
                                         success: function (rt, st, xhr) {
                                             if (st == "error") {
                                                 alert("Error :" + xhr.status + " " + xhr.statusText);
                                             }
                                             else {
                                                
                                                 $("#partial").html(rt);
                                                 
                                             }
                                         }
                                     });
                                 }

                             }
                         }
                     });

                     return false;
                 });
             });
</script>
<div class="form-inline">
    @using (Html.BeginForm("result", "Clint", FormMethod.Post, new { id = "Showcarform" }))
    {
        <div class="form-group">
            @Html.LabelFor(c => c.car.categorytypeid)
            @Html.DropDownListFor(c => c.car.categorytypeid, new SelectList(Model.categories, "id", "Name"), " select type  of car", new { @class = "form-control" })
            @Html.ValidationMessageFor(c => c.car.categorytypeid,"", new { style = "display:block" })
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.car.color)
@{if (Model.colorstate == 1)
       {
            @Html.TextBoxFor(c => c.car.color, new { @class = "form-control", id = "input-validation-error" })
            @Html.ValidationMessageFor(c => c.car.color, "", new { style = "display:block" })
            <span class="field-validation-error" style="display:block"> @Model.messageerror </span>
       }
  else
  {
          @Html.TextBoxFor(c => c.car.color, new { @class = "form-control" })
          @Html.ValidationMessageFor(c => c.car.color, "", new { style = "display:block" })
  }
}
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.car.Model)
            @Html.TextBoxFor(c => c.car.Model, new { @class = "form-control" })
            @Html.ValidationMessageFor(c => c.car.Model, "", new { style = "display:block" })
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.car.NumberOfChairs)
            @Html.TextBoxFor(c => c.car.NumberOfChairs, new { @class = "form-control" })
            @Html.ValidationMessageFor(c => c.car.NumberOfChairs, "", new { style = "display:block" })
        </div>
        <div class="form-group">
            @Html.LabelFor(c => c.car.RentAmount)
            @Html.TextBoxFor(c => c.car.RentAmount, new { @class = "form-control" })
            @Html.ValidationMessageFor(c => c.car.RentAmount, "", new { style = "display:block" })
            @Html.HiddenFor(c => c.id)
        </div>
        @Html.AntiForgeryToken()
        <input type="submit" class="btn btn-primary" value="Show Cars" id="submitformshow" />
    }
</div>